apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-deployment
  labels:
    app: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: hirohit28/springbootapp:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 600Mi
          requests:
            cpu: 500m
            memory: 300Mi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-container-deployment
  labels:
    app: jenkins-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-container
  template:
    metadata:
      labels:
        app: jenkins-container
    spec:
      containers:
      - name: jenkins-container
        image: hirohit28/myjenkins:v1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 2048m
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 500Mi


---

apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
spec:
  selector:
    app: springboot-app
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8080
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-container-service
spec:
  selector:
    app: jenkins-container
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer

